import{S as h,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const g="46078376-453970e5bd186575301de3a15",p="https://pixabay.com/api/";function y(n,t=1){const i=`${p}?key=${g}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=12`;return fetch(i).then(o=>{if(!o.ok)throw new Error("Error fetching images");return o.json()}).catch(o=>{throw console.error(o),o})}const u=document.querySelector(".gallery");let c;function b(n){const t=n.map(({webformatURL:i,largeImageURL:o,tags:e,likes:r,views:s,comments:d,downloads:m})=>`
      <a class="gallery__item" href="${o}">
        <img class="gallery__image" src="${i}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${s}</p>
          <p><b>Comments</b> ${d}</p>
          <p><b>Downloads</b> ${m}</p>
        </div>
      </a>`).join("");u.innerHTML=t,c?c.refresh():c=new h(".gallery a")}function L(){u.innerHTML=""}const $=document.querySelector("#search-form"),f=document.querySelector(".loader");let l="",w=1;$.addEventListener("submit",S);function S(n){if(n.preventDefault(),l=n.currentTarget.elements.searchQuery.value.trim(),l===""){a.error({title:"Error",message:"Please enter a search query."});return}L(),q(),y(l,w).then(t=>{t.hits.length===0?a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):b(t.hits)}).catch(t=>{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}).finally(()=>{E()})}function q(){f.classList.remove("hidden")}function E(){f.classList.add("hidden")}
//# sourceMappingURL=index.js.map
